# EdgeFlow Trader — Risk Parameters
startingBalance:         100.00      # USD
startingLots:            0.25        # lots

lotIncrease:
  triggerBalanceStep:    200.00      # USD
  lotsPerStep:           0.25        # lots
  hardMaxLots:           50          # absolute ceiling

maxRiskPerTradePct:      10.0        # % equity at risk
dailyLossCapPct:         0.0         # 0 = disabled
maxOpenTrades:           4           # simultaneous positions

# NEW  — maximum price drift the EA will allow (points, not pips)
slippagePoints:          3
